# matching_engine.py

from datetime import datetime, timezone
from typing import List, Optional
from uuid import uuid4

from order_book import OrderBook
from order_types import Order
from order_types import OrderStatus
from order_types import OrderType
from order_types import Side
from order_types import Trade

from risk.risk_engine import RiskEngine


class MatchingEngine:
    def __init__(
        self,
        order_book: OrderBook,
        risk_engine: Optional[RiskEngine] = None,
    ):
        self.order_book = order_book
        self.risk_engine = risk_engine

    def process_order(self, order: Order) -> List[Trade]:
        """
        Process a new incoming order.

        Returns:
            List[Trade] generated by matching.
            Empty list if order is rejected by risk engine
            or no match occurs.
        """

        # ----------------------------------------------------------
        # Risk gate — runs BEFORE matching logic touches the order
        # ----------------------------------------------------------

        if self.risk_engine is not None:
            mid_price = self._get_mid_price()
            result = self.risk_engine.check(order, mid_price)

            if not result.approved:
                order.status = OrderStatus.REJECTED
                print(f"REJECTED {order.order_id}: {result.reason}")
                return []

        trades: List[Trade] = []

        while order.remaining_quantity > 0:

            opposite = self._get_best_opposite(order)

            if opposite is None:
                break

            if not self._can_match(order, opposite):
                break

            fill_qty = min(
                order.remaining_quantity,
                opposite.remaining_quantity
            )

            trade_price = self._trade_price(
                incoming_order=order,
                resting_order=opposite
            )

            trade = Trade(
                trade_id=str(uuid4()),
                symbol=order.symbol,
                buyer_order_id=(
                    order.order_id
                    if order.side == Side.BUY
                    else opposite.order_id
                ),
                seller_order_id=(
                    order.order_id
                    if order.side == Side.SELL
                    else opposite.order_id
                ),
                quantity=fill_qty,
                price=trade_price,
                timestamp=datetime.now(timezone.utc)
            )

            trades.append(trade)

            order.remaining_quantity -= fill_qty
            opposite.remaining_quantity -= fill_qty

            self._update_status(order)
            self._update_status(opposite)

            # ----------------------------------------------------------
            # Update position tracking after every fill
            # ----------------------------------------------------------

            if self.risk_engine is not None:
                for rule in self.risk_engine.rules:
                    if hasattr(rule, "on_trade_fill"):
                        rule.on_trade_fill(
                            order.symbol, order.side, fill_qty
                        )
                        rule.on_trade_fill(
                            opposite.symbol,
                            (
                                Side.SELL
                                if order.side == Side.BUY
                                else Side.BUY
                            ),
                            fill_qty,
                        )

            if opposite.remaining_quantity == 0:
                self.order_book.cancel_order(
                    opposite.order_id
                )

        if order.remaining_quantity > 0:

            if order.order_type == OrderType.LIMIT:
                self.order_book.add_order(order)

        return trades

    def _get_mid_price(self) -> float:
        best_bid = self.order_book.get_best_bid()
        best_ask = self.order_book.get_best_ask()

        if best_bid and best_ask:
            return (best_bid.price + best_ask.price) / 2
        if best_bid:
            return best_bid.price
        if best_ask:
            return best_ask.price
        return 0.0

    def _get_best_opposite(self, order: Order):

        if order.side == Side.BUY:
            return self.order_book.get_best_ask()

        return self.order_book.get_best_bid()

    def _can_match(self, incoming: Order, resting: Order) -> bool:

        if incoming.order_type == OrderType.MARKET:
            return True

        if resting.order_type == OrderType.MARKET:
            return True

        if incoming.side == Side.BUY:
            return incoming.price >= resting.price

        return incoming.price <= resting.price

    def _trade_price(self, incoming_order: Order, resting_order: Order) -> float:
        return resting_order.price

    def _update_status(self, order: Order):

        if order.remaining_quantity == 0:
            order.status = OrderStatus.FILLED

        elif order.remaining_quantity < order.quantity:
            order.status = OrderStatus.PARTIAL

        else:
            order.status = OrderStatus.NEW
