# matching_engine.py

from datetime import datetime, timezone
from typing import List
from uuid import uuid4

from order_book import OrderBook
from order_types import Order
from order_types import OrderStatus
from order_types import OrderType
from order_types import Side
from order_types import Trade


class MatchingEngine:
    def __init__(self, order_book: OrderBook):
        self.order_book = order_book

    def process_order(self, order: Order) -> List[Trade]:
        """
        Process a new incoming order.

        Returns:
            List[Trade] generated by matching.
        """

        trades: List[Trade] = []

        while order.remaining_quantity > 0:

            opposite = self._get_best_opposite(order)

            if opposite is None:
                break

            if not self._can_match(order, opposite):
                break

            fill_qty = min(
                order.remaining_quantity,
                opposite.remaining_quantity
            )

            trade_price = self._trade_price(
                incoming_order=order,
                resting_order=opposite
            )

            trade = Trade(
                trade_id=str(uuid4()),
                symbol=order.symbol,
                buyer_order_id=(
                    order.order_id
                    if order.side == Side.BUY
                    else opposite.order_id
                ),
                seller_order_id=(
                    order.order_id
                    if order.side == Side.SELL
                    else opposite.order_id
                ),
                quantity=fill_qty,
                price=trade_price,
                timestamp=datetime.now(timezone.utc)
            )

            trades.append(trade)

            # --------------------------------------------------
            # Update quantities
            # --------------------------------------------------

            order.remaining_quantity -= fill_qty
            opposite.remaining_quantity -= fill_qty

            self._update_status(order)
            self._update_status(opposite)

            # --------------------------------------------------
            # Remove filled resting order
            # --------------------------------------------------

            if opposite.remaining_quantity == 0:
                self.order_book.cancel_order(
                    opposite.order_id
                )

        # ------------------------------------------------------
        # If incoming order still has quantity remaining,
        # add it to the book (LIMIT only)
        # ------------------------------------------------------

        if order.remaining_quantity > 0:

            if order.order_type == OrderType.LIMIT:
                self.order_book.add_order(order)

        return trades

    def _get_best_opposite(self, order: Order):

        if order.side == Side.BUY:
            return self.order_book.get_best_ask()

        return self.order_book.get_best_bid()

    def _can_match(
        self,
        incoming: Order,
        resting: Order
    ) -> bool:

        # Market orders always match

        if incoming.order_type == OrderType.MARKET:
            return True

        if resting.order_type == OrderType.MARKET:
            return True

        # Limit order crossing logic

        if incoming.side == Side.BUY:
            return incoming.price >= resting.price

        return incoming.price <= resting.price

    def _trade_price(
        self,
        incoming_order: Order,
        resting_order: Order
    ) -> float:
        """
        Exchanges typically execute at the
        resting order's price.
        """

        return resting_order.price

    def _update_status(self, order: Order):

        if order.remaining_quantity == 0:
            order.status = OrderStatus.FILLED

        elif order.remaining_quantity < order.quantity:
            order.status = OrderStatus.PARTIAL

        else:
            order.status = OrderStatus.NEW
